revert workflow changes

diff --git a/.github/workflows/terraform-module-ci.yaml b/.github/workflows/terraform-module-ci.yaml
--- a/.github/workflows/terraform-module-ci.yaml
+++ b/.github/workflows/terraform-module-ci.yaml
@@ -45,31 +45,6 @@ env:
   TF_IN_AUTOMATION: true
 
 jobs:
-  generate-docs:
-    name: Update README.md
-    runs-on: ubuntu-latest
-    steps:
-      - name: "📥 Checkout"
-        uses: actions/checkout@v4
-        with:
-          ref: ${{ github.event.pull_request.head.ref }}
-
-      - name: "📝 Validate and update README.md"
-        id: update-readme
-        # TODO revert to @v0
-        uses: dsb-norge/github-actions-terraform/terraform-docs@tfdocs-fix
-        with:
-          readme-file-path: ${{ inputs.readme-file-path }}
-        continue-on-error: true
-
-      - name: "🧐 Validation outcome: 📝 Update docs"
-        run: |
-          if [ ! "${{ steps.update-readme.outcome }}" == 'success' ]; then
-            echo "::error title=Update README.md failed::Outcome of update README.md step was '${{ steps.update-readme.outcome }}'!"
-            exit 1
-          fi
-        continue-on-error: false
-
   create-matrix:
     name: Create job matrix
     runs-on: [self-hosted, dsb-terraformer, linux, x64]
@@ -89,8 +64,7 @@ jobs:
 
       - name: "🎰 Create env matrix"
         id: create-matrix
-        # TODO revert to @v0
-        uses: dsb-norge/github-actions-terraform/create-tftest-matrix@tfdocs-fix
+        uses: dsb-norge/github-actions-terraform/create-tftest-matrix@v0
 
       - name: "📥 Setup Terraform"
         uses: hashicorp/setup-terraform@v3
@@ -101,13 +75,11 @@ jobs:
 
       - name: "🗄️ Setup Terraform provider plugin cache"
         id: setup-terraform-cache
-        # TODO revert to @v0
-        uses: dsb-norge/github-actions-terraform/setup-terraform-plugin-cache@tfdocs-fix
+        uses: dsb-norge/github-actions-terraform/setup-terraform-plugin-cache@v0
 
       - name: "📥 Setup TFLint"
         id: setup-tflint
-        # TODO revert to @v0
-        uses: dsb-norge/github-actions-terraform/setup-tflint@tfdocs-fix
+        uses: dsb-norge/github-actions-terraform/setup-tflint@v0
         with:
           tflint-version: ${{ inputs.tflint-version }}
           working-directory: ${{ github.workspace }}
@@ -120,8 +92,7 @@ jobs:
 
       - name: ⚙️ Terraform Init
         id: init
-        # TODO revert to @v0
-        uses: dsb-norge/github-actions-terraform/terraform-init@tfdocs-fix
+        uses: dsb-norge/github-actions-terraform/terraform-init@v0
         with:
           working-directory: ${{ github.workspace }}
           additional-dirs-json: null
@@ -130,8 +101,7 @@ jobs:
 
       - name: 🖌 Terraform Format
         id: fmt
-        # TODO revert to @v0
-        uses: dsb-norge/github-actions-terraform/terraform-fmt@tfdocs-fix
+        uses: dsb-norge/github-actions-terraform/terraform-fmt@v0
         with:
           working-directory: ${{ github.workspace }}
           format-check-in-root-dir: true
@@ -139,16 +109,14 @@ jobs:
     
       - name: ✔ Terraform Validate
         id: validate
-        # TODO revert to @v0
-        uses: dsb-norge/github-actions-terraform/terraform-validate@tfdocs-fix
+        uses: dsb-norge/github-actions-terraform/terraform-validate@v0
         with:
           working-directory: ${{ github.workspace }}
         continue-on-error: true # allow job to continue, step outcome is evaluated later
 
       - name: 🧹 Lint with TFLint
         id: lint
-        # TODO revert to @v0
-        uses: dsb-norge/github-actions-terraform/lint-with-tflint@tfdocs-fix
+        uses: dsb-norge/github-actions-terraform/lint-with-tflint@v0
         with:
           working-directory: ${{ github.workspace }}
         continue-on-error: true # allow job to continue, step outcome is evaluated later
@@ -156,8 +124,7 @@ jobs:
       - name: 📝 Create validation summary
         id: create-validation-summary
         if: github.event_name == 'pull_request'
-        # TODO revert to @v0
-        uses: dsb-norge/github-actions-terraform/create-validation-summary@tfdocs-fix
+        uses: dsb-norge/github-actions-terraform/create-validation-summary@v0
         with:
           environment-name: "module"
           plan-txt-output-file: ""
@@ -236,8 +203,7 @@ jobs:
     
       - name: ⚙️ Terraform Init
         id: init
-        # TODO revert to @v0
-        uses: dsb-norge/github-actions-terraform/terraform-init@tfdocs-fix
+        uses: dsb-norge/github-actions-terraform/terraform-init@v0
         with:
           working-directory: ${{ github.workspace }}
           additional-dirs-json: null
@@ -246,8 +212,7 @@ jobs:
 
       - name: 🧪 Terraform Test
         id: test
-        # TODO revert to @v0
-        uses: dsb-norge/github-actions-terraform/terraform-test@tfdocs-fix
+        uses: dsb-norge/github-actions-terraform/terraform-test@v0
         with:
           test-file: ${{ matrix.test-file }}
         continue-on-error: true # allow job to continue, step outcome is evaluated later
@@ -255,8 +220,7 @@ jobs:
       - name: 📝 Create test report
         id: create-test-report
         if: github.event_name == 'pull_request'
-        # TODO revert to @v0
-        uses: dsb-norge/github-actions-terraform/create-test-report@tfdocs-fix
+        uses: dsb-norge/github-actions-terraform/create-test-report@v0
         with:
           test-out-file: ${{ steps.test.outputs.json }}
           status-init: ${{ steps.init.outcome }}
@@ -294,12 +258,39 @@ jobs:
           fi
         continue-on-error: false
 
+  generate-docs:
+    name: Update README.md
+    needs: terraform-module-ci
+    runs-on: ubuntu-latest
+    if: needs.terraform-module-ci.result == 'success'
+    steps:
+      - name: "📥 Checkout"
+        uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event.pull_request.head.ref }}
+
+      - name: "📝 Validate and update README.md"
+        id: update-readme
+        uses: dsb-norge/github-actions-terraform/terraform-docs@v0
+        with:
+          readme-file-path: ${{ inputs.readme-file-path }}
+        continue-on-error: true
+
+      - name: "🧐 Validation outcome: 📝 Update docs"
+        run: |
+          if [ ! "${{ steps.update-readme.outcome }}" == 'success' ]; then
+            echo "::error title=Update README.md failed::Outcome of update README.md step was '${{ steps.update-readme.outcome }}'!"
+            exit 1
+          fi
+        continue-on-error: false
+
+
     # create a global result indicating if workflow steps succeeded or not,
     # handy for branch protection rules
   conclusion:
     if: always()
     name: "Terraform conclusion"
-    needs: [create-matrix, terraform-module-ci]
+    needs: [create-matrix, terraform-module-ci, generate-docs]
     runs-on: ubuntu-latest # no need to schedule this on our own runners
     defaults:
       run:
