change workflow order

diff --git a/.github/workflows/terraform-module-ci.yaml b/.github/workflows/terraform-module-ci.yaml
--- a/.github/workflows/terraform-module-ci.yaml
+++ b/.github/workflows/terraform-module-ci.yaml
@@ -45,6 +45,33 @@ env:
   TF_IN_AUTOMATION: true
 
 jobs:
+  generate-docs:
+    name: Update README.md
+    needs: terraform-module-ci
+    runs-on: ubuntu-latest
+    if: needs.terraform-module-ci.result == 'success'
+    steps:
+      - name: "📥 Checkout"
+        uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event.pull_request.head.ref }}
+
+      - name: "📝 Validate and update README.md"
+        id: update-readme
+        # TODO revert to @v0
+        uses: dsb-norge/github-actions-terraform/terraform-docs@tfdocs-fix
+        with:
+          readme-file-path: ${{ inputs.readme-file-path }}
+        continue-on-error: true
+
+      - name: "🧐 Validation outcome: 📝 Update docs"
+        run: |
+          if [ ! "${{ steps.update-readme.outcome }}" == 'success' ]; then
+            echo "::error title=Update README.md failed::Outcome of update README.md step was '${{ steps.update-readme.outcome }}'!"
+            exit 1
+          fi
+        continue-on-error: false
+        
   create-matrix:
     name: Create job matrix
     runs-on: [self-hosted, dsb-terraformer, linux, x64]
@@ -268,58 +295,6 @@ jobs:
             exit 1
           fi
         continue-on-error: false
-
-  generate-docs:
-    name: Update README.md
-    needs: terraform-module-ci
-    runs-on: ubuntu-latest
-    if: needs.terraform-module-ci.result == 'success'
-    steps:
-      - name: "📥 Checkout"
-        uses: actions/checkout@v4
-        with:
-          ref: ${{ github.event.pull_request.head.ref }}
-
-      - name: "📝 Validate and update README.md"
-        id: update-readme
-        # TODO revert to @v0
-        uses: dsb-norge/github-actions-terraform/terraform-docs@tfdocs-fix
-        with:
-          readme-file-path: ${{ inputs.readme-file-path }}
-        continue-on-error: true
-
-      - name: "🧐 Validation outcome: 📝 Update docs"
-        run: |
-          if [ ! "${{ steps.update-readme.outcome }}" == 'success' ]; then
-            echo "::error title=Update README.md failed::Outcome of update README.md step was '${{ steps.update-readme.outcome }}'!"
-            exit 1
-          fi
-        continue-on-error: false
-
-      - name: "🔄 Check for changes"
-        id: check-changes
-        run: |
-          if [ -n "$(git status --porcelain)" ]; then
-            echo "changes=true" >> $$GITHUB_OUTPUT
-          else
-            echo "changes=false" >> $$GITHUB_OUTPUT
-          fi
-  
-      - name: "🔄 Push changes"
-        if: ${{ steps.check-changes.outputs.changes == 'true' }}
-        run: |
-          git config --global user.email "github-actions[bot]@users.noreply.github.com"
-          git config --global user.name "github-actions[bot]"
-          git add .
-          git commit -m "Update README.md with Terraform docs"
-          git push origin ${{ github.event.pull_request.head.ref }}
-  
-      - name: "🔄 Update local branch"
-        if: ${{ steps.check-changes.outputs.changes == 'true' }}
-        run: |
-          git fetch origin
-          git reset --hard origin/${{ github.event.pull_request.head.ref }}
-
 
     # create a global result indicating if workflow steps succeeded or not,
     # handy for branch protection rules
